title: Jeremy Fletcher Links
description: Usefull links and bookmarks
root: /
baseurl: /
url: https://links.jeremyfletcher.net
show_downloads: false
google_analytics:
theme: jekyll-theme-minima
readme_index:
  enabled:          false
