title: Jeremy Fletcher Links
description: Usefull links and bookmarks
domain: links.jeremyfletcher.net       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://links.jeremyfletcher.net  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /
show_downloads: false
google_analytics:
theme: minima
